### ISSUE TITLE
Error instantiate ComplexConv2D

### ISSUE THREAD

**Issue by NullCodex** [JesperDramsch/keras-complex#10]
```
import complexnn

import keras
from keras import models
from keras import layers
from keras import optimizers

model = models.Sequential()

model.add(complexnn.conv.ComplexConv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 3), data_format='channels_last'))
model.add(complexnn.bn.ComplexBatchNormalization())
model.add(layers.MaxPooling2D((2, 2), padding='same'))

model.compile(optimizer=optimizers.Adam(), loss='mse')
```

Using the above example, I am getting
```
ValueError: Input 0 is incompatible with layer complex_conv2d_8: expected axis -1 of input shape to have value 2 but got shape (None, 28, 28, 3)
```

Is this only supposed to work when the channel shape is 2? I see that https://github.com/JesperDramsch/keras-complex/blob/master/complexnn/conv.py#L732 has documentation for RGB images.

**Comment by YannLemonnier** [comment]
Looks like a copy / paste trail from original code https://github.com/tensorflow/tensorflow/blob/fcc4b966f1265f466e82617020af93670141b009/tensorflow/python/keras/layers/convolutional.py#L524

**Comment by NullCodex** [comment]
Is there a way to use the complexconv2d where the channel data is RGB? it does not look like it works with grayscale either.

**Comment by JesperDramsch** [comment]
The complex convolution expects the real-valued and complex-valued complement of the data in two feature maps. A complex MNIST would have the shape (28, 28, 2) for a greyscale image but the data has to be provided explicitly.

It would probably better say that it should be a multiple of 2.

Here's an example, where I used a Hilberttransformed data set to get complex data.
https://github.com/JesperDramsch/Complex-CNN-Seismic

**Comment by NullCodex** [comment]
From looking at https://github.com/JesperDramsch/Complex-CNN-Seismic/blob/master/src/data_prep.py, the data is of two dimension where the first dimension is the real part and the second dimension is the imaginary part where it's represented using real number via np.imag. For instance if i took the fft of a grayscale image, the two dimension would be the real part and imag part represented as a real number. Is that correct?

**Comment by JesperDramsch** [comment]
Pretty much, yes.

It's [x, y, (real, imag)]


As per:
https://github.com/JesperDramsch/keras-complex/blob/dc4b986acc69cbe7351e475882ed269381d6f594/complexnn/conv.py#L378

the split (r,i,r,i,r,i) is wrong. It should have been (r,r,r,i,i,i). Sorry.

Am Di., 1. Dez. 2020 um 00:21 Uhr schrieb NullCodex <
notifications@github.com>:

**Comment by JesperDramsch** [comment]
> It's [x, y, (real, imag)]
> ~~ and for RGB it should then be [x, y, (r, i, r, i, r, i)] ~~

As per:
https://github.com/JesperDramsch/keras-complex/blob/dc4b986acc69cbe7351e475882ed269381d6f594/complexnn/conv.py#L378

the split (r,i,r,i,r,i) is wrong. It should have been (r,r,r,i,i,i). Sorry.
