### ISSUE TITLE
Issues with Complex Dense Layers

### ISSUE THREAD

**Issue by kevinchang95** [JesperDramsch/keras-complex#11]
Hello, 

I was trying to use the complexnn.dense.ComplexDense() layer to form an ANN with complex number. The input data is 432 60-point complex arrays and have a shape(432,120) which I concatenate the Real and Imaginary part. My network structure is as follows:
![image](https://user-images.githubusercontent.com/33199797/102131880-79e32a80-3e18-11eb-9776-4223d8f6713e.png)

Then I compiled and fit the network while it gives me error like this:
![image](https://user-images.githubusercontent.com/33199797/102132101-c75f9780-3e18-11eb-9b15-6d804a5a5288.png)

I would like to ask that is the problem coming from the wrong _input_dim_ , wrong _batch_size_ assignment, or bad output neuron setting? 

Also, is there any available examples for the ComplexDense() layer application? Since I only saw ComplexConv2D() example in README.

Very appreciate it!

**Comment by JesperDramsch** [comment]
It looks like a problem with your last layer. What does your `y_train` look like?

**Comment by kevinchang95** [comment]
Thank you for the reply!

My `y_train` is a scalar which is obtained by the magnitude of the multiplication of complex input arrays and complex weight arrays:
![image](https://user-images.githubusercontent.com/33199797/102154593-54b5e280-3e3f-11eb-816b-e63bc6bb60c8.png)

Oops, the ground truth output should also be real and imaginary part concatenation, right? I think this might be the answer? If there is one neuron at the end, the output should be (None,2) right?

Thanks.

**Comment by JesperDramsch** [comment]
Yes, either that or you change your last layer to a vanilla Dense layer with (None, 1).

**Comment by kevinchang95** [comment]
Thank you! I added an extra Dense layer and it works pretty well! Appreciate it!
