### ISSUE TITLE
Interpretation of complex_conv2d layer's output

### ISSUE THREAD

**Issue by ShubhankarRawat** [JesperDramsch/keras-complex#13]
First of all, thank you for the brilliant repo.

I have a doubt regarding the interpretation of the output of the complex_conv2d layer (cc2l). A cc2l with 64 kernels has an output of (None, None, None, 128), meaning we have 64 real and 64 imaginary matrices. I want to know what is the correct set of r and i, i.e., are the first 64 matrices real and rest imaginary or the odd-numbered (1, 3, 5...) ones are real and even-numbered (2, 4, 6,...) ones imaginary.

**Comment by hosseybposh** [comment]
hi,
I'm not a contributor but I checked the code and the first half is real and the second half is imaginary. You can see that in the `get_realpart` method.
