### ISSUE TITLE
ImportErros when import complexnn

### ISSUE THREAD

**Issue by Buffy-nevc** [JesperDramsch/keras-complex#14]
Hi,

I have installed keras-complex using command "pip install keras-complex".

But when I try to import complexnn, the following ImportError was reported:
    from keras.layers.convolutional import _Conv
ImportError: cannot import name '_Conv'

I had a quick search online and there seems to be some compatibility issue between keras and tensorlfow, maybe? 
But I am not sure how to fix it. Is there a specific keras+tensorflow version combo we are expecting?

Thanks,

Buffy

**Comment by NEGU93** [comment]
Normally a preceding underscore (`_`) is not meant to be imported. Can you import other layers? Do they work? Try the script on the readme.

**Comment by SherryYang1122** [comment]
I met the same problem...I have thought this bug fixed in the new version, however, it is not. One stupid method is to use the old version of Deep Complex Networks by 
!pip install keras==2.2.4
!pip install tensorflow==1.13.1
