### ISSUE TITLE
Basic Usage

### ISSUE THREAD

**Issue by tkoch96** [JesperDramsch/keras-complex#3]
I'm wondering what the assumed input dimensions are, if the input data is complex. For example, if I want to perform a complex 1D convolution on complex data, would the assumed data input be 

[batch_index, 2, N] or [batch_index, N, 2] or [batch_index, 2*N]  where N is the number of complex numbers?

As far as I can tell, your examples demonstrate leveraging complex operations on intrinsically real data, rather than intrinsically complex data, so I was hoping for some clarification.

**Comment by JesperDramsch** [comment]
I think the documentation should explain how to interpret the math.

https://keras-complex.readthedocs.io/math.html

**Comment by tkoch96** [comment]
Yes thank you, that's what I was looking for
